// <auto-generated />
using System;
using Api.KapiDunyasi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.KapiDunyasi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117095535_UpdateUserRoleDefault")]
    partial class UpdateUserRoleDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Blog.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExcerptTR")
                        .HasColumnType("text")
                        .HasColumnName("excerpt_tr");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<string[]>("TagsTR")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags_tr");

                    b.Property<string>("TitleTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_tr");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TagsTR");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TagsTR"), "gin");

                    b.ToTable("blog_posts", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionTR")
                        .HasColumnType("text")
                        .HasColumnName("description_tr");

                    b.Property<string>("NameTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_tr");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Contacts.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("contact_messages", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Faqs.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ATR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("a_tr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("QTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("q_tr");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("faqs", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_name");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_type");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_no");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Policies.PolicyContent", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("BodyTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_tr");

                    b.Property<string>("TitleTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_tr");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("policy_contents", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("BadgesTR")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("badges_tr");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FireResistant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fire_resistant");

                    b.PrimitiveCollection<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("images");

                    b.Property<string>("NameTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_tr");

                    b.Property<string>("SeriesTR")
                        .HasColumnType("text")
                        .HasColumnName("series_tr");

                    b.Property<string>("ShippingTR")
                        .HasColumnType("text")
                        .HasColumnName("shipping_tr");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("StockCount")
                        .HasColumnType("integer")
                        .HasColumnName("stock_count");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stock_status");

                    b.PrimitiveCollection<string[]>("TagsTR")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags_tr");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WarrantyTR")
                        .HasColumnType("text")
                        .HasColumnName("warranty_tr");

                    b.HasKey("Id");

                    b.HasIndex("BadgesTR");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BadgesTR"), "gin");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FireResistant");

                    b.HasIndex("SeriesTR");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StockStatus");

                    b.HasIndex("TagsTR");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TagsTR"), "gin");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.References.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CityTR")
                        .HasColumnType("text")
                        .HasColumnName("city_tr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionTR")
                        .HasColumnType("text")
                        .HasColumnName("description_tr");

                    b.Property<string>("ProjectNameTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_name_tr");

                    b.Property<string>("TypeTR")
                        .HasColumnType("text")
                        .HasColumnName("type_tr");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CityTR");

                    b.HasIndex("Year");

                    b.ToTable("references", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Showrooms.Showroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressTR")
                        .HasColumnType("text")
                        .HasColumnName("address_tr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MapEmbedUrl")
                        .HasColumnType("text")
                        .HasColumnName("map_embed_url");

                    b.Property<string>("NameTR")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_tr");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkingHoursTR")
                        .HasColumnType("text")
                        .HasColumnName("working_hours_tr");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("showrooms", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Blog.BlogPost", b =>
                {
                    b.OwnsMany("Api.KapiDunyasi.Domain.Blog.BlogContentSection", "ContentTR", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BodyTR")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body_tr");

                            b1.Property<string>("HeadingTR")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("heading_tr");

                            b1.Property<Guid>("blog_post_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("blog_post_id");

                            b1.ToTable("blog_content_sections", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("blog_post_id");
                        });

                    b.Navigation("ContentTR");
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Categories.Category", b =>
                {
                    b.HasOne("Api.KapiDunyasi.Domain.Categories.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Orders.Order", b =>
                {
                    b.OwnsMany("Api.KapiDunyasi.Domain.Orders.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("Image")
                                .HasColumnType("text")
                                .HasColumnName("image");

                            b1.Property<string>("NameTR")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name_tr");

                            b1.Property<decimal>("Price")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<int>("Qty")
                                .HasColumnType("integer")
                                .HasColumnName("qty");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("VariantColor")
                                .HasColumnType("text")
                                .HasColumnName("variant_color");

                            b1.Property<string>("VariantDirection")
                                .HasColumnType("text")
                                .HasColumnName("variant_direction");

                            b1.Property<string>("VariantFrame")
                                .HasColumnType("text")
                                .HasColumnName("variant_frame");

                            b1.Property<string>("VariantSize")
                                .HasColumnType("text")
                                .HasColumnName("variant_size");

                            b1.Property<string>("VariantThickness")
                                .HasColumnType("text")
                                .HasColumnName("variant_thickness");

                            b1.Property<Guid>("order_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.HasIndex("order_id");

                            b1.ToTable("order_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("order_id");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Products.Product", b =>
                {
                    b.OwnsOne("Api.KapiDunyasi.Domain.Products.ProductPrice", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Max")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_max");

                            b1.Property<decimal?>("Min")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_min");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_type");

                            b1.Property<decimal?>("Value")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_value");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Min", "Max");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Api.KapiDunyasi.Domain.Products.ProductSpecs", "Specs", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<string[]>("ColorOptionsTR")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("specs_color_options_tr");

                            b1.PrimitiveCollection<string[]>("FrameOptions")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("specs_frame_options");

                            b1.Property<string>("MaterialTR")
                                .HasColumnType("text")
                                .HasColumnName("specs_material_tr");

                            b1.PrimitiveCollection<string[]>("OpeningDirectionsTR")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("specs_opening_directions_tr");

                            b1.PrimitiveCollection<string[]>("Sizes")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("specs_sizes");

                            b1.Property<string>("SurfaceTR")
                                .HasColumnType("text")
                                .HasColumnName("specs_surface_tr");

                            b1.PrimitiveCollection<string[]>("ThicknessOptions")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("specs_thickness_options");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Specs")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.KapiDunyasi.Domain.Categories.Category", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
